import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { fetchCars } from "@/utils";

export const metadata = {
  title: "CarHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="relative">
          <Navbar />
          {children}
          <Footer />
      </body>
    </html>
  );
}
